import type { CullingBounds } from "@engine/core/render-pipeline/passes/render-world/render/culling/utils";
import type { SpriteRenderRecord } from "@engine/core/render-pipeline/passes/render-world/sprite-render-record";
import type { EntityId } from "@engine/ecs/entity";
import type { UserWorld } from "@engine/ecs/world";
import type { EngineFrameAllocatorRegistry, InternalFrameAllocator, RenderQueue } from "@engine/render";

export function queueSpriteCommand(
  entityId: EntityId,
  world: UserWorld,
  layer: number,
  zOrder: number,
  spriteRecordIndex: number,
  queue: RenderQueue,
  frameAllocator: InternalFrameAllocator<EngineFrameAllocatorRegistry>,
): void {
  const command = frameAllocator.acquire("engine:render-command");
  command.type = "sprite-entity";
  command.world = world;
  command.entityId = entityId;
  command.shape = null;
  command.layer = layer;
  command.zOrder = zOrder;
  command.spriteRecordIndex = spriteRecordIndex;

  queue.add(command);
}

export function pushSpriteRecord(records: SpriteRenderRecord[], record: SpriteRenderRecord): number {
  records.push(record);
  return records.length - 1;
}

/**
 * Resolves a culling signature based on the provided culling bounds and interpolation alpha.
 * A Culling Signature is a numeric value that represents the culling state for a particular render command.
 * It is used to determine if a render command should be culled based on the current culling bounds and interpolation alpha.
 * The signature is generated by quantizing the culling bounds and alpha into integers and combining them into a single number.
 * 
 * @param cullingBounds The bounds used for culling calculations.
 * @param alpha The interpolation alpha used for blending between frames.
 * @returns A numeric culling signature that can be used for efficient culling comparisons.
 */
export function resolveCullingSignature(cullingBounds: CullingBounds | null, alpha: number,): number {
  if (!cullingBounds) {
    return Math.round(alpha * 1000);
  }

  const minX = Math.round(cullingBounds.minX * 1000);
  const maxX = Math.round(cullingBounds.maxX * 1000);
  const minY = Math.round(cullingBounds.minY * 1000);
  const maxY = Math.round(cullingBounds.maxY * 1000);
  const quantizedAlpha = Math.round(alpha * 1000);

  return (((minX * 31 + maxX) * 31 + minY) * 31 + maxY) * 31 + quantizedAlpha;
}